#include <array>
#include <cassert>
#include <chrono>
#include <functional>
#include <thread>
#include "display/display_runtime.hpp"
#include "display/display_rasterizer.hpp"
using namespace streamdeck::display;
namespace {
std::array<uint8_t,56> command(Opcode op,uint32_t generation,std::size_t&length){std::array<uint8_t,56>p{};encode_envelope(p.data(),{1,0,uint8_t(op),uint8_t(AckRequired),generation});length=8;return p;}
Error send(DisplayRuntime&r,std::array<uint8_t,56>&p,std::size_t n,std::array<uint8_t,56>&out,std::size_t&outn,uint32_t now=10){return r.handle(p.data(),n,out.data(),outn,now);}
uint32_t crc32(const uint8_t*d,std::size_t n){uint32_t c=0xFFFFFFFFu;for(std::size_t i=0;i<n;i++){c^=d[i];for(int b=0;b<8;b++)c=(c>>1)^(0xEDB88320u&uint32_t(0-int(c&1)));}return c^0xFFFFFFFFu;}
void node_body(uint8_t*b,uint16_t id,uint16_t parent,NodeKind kind,int16_t x,int16_t y,int16_t w,int16_t h,int16_t z=0){write_u16(b,id);write_u16(b+2,parent);b[4]=uint8_t(kind);b[5]=1;write_i16(b+6,z);write_i16(b+8,x);write_i16(b+10,y);write_i16(b+12,w);write_i16(b+14,h);write_u16(b+16,0xFFFF);b[22]=255;}
class PhysicalBackend final:public IDisplayBackend{public:void present(const Scene&,const AssetPool&,bool,const Rect*,std::size_t)override{}uint8_t state()const override{return 1;}bool physical()const override{return true;}};
class SlowBackend final:public IDisplayBackend{public:void present(const Scene&s,const AssetPool&,bool,const Rect*,std::size_t)override{++draw_count;last_generation=s.generation;std::this_thread::sleep_for(std::chrono::milliseconds(100));auto callback=service;service={};if(callback)callback();std::this_thread::sleep_for(std::chrono::milliseconds(200));}uint8_t state()const override{return 1;}bool physical()const override{return true;}std::function<void()>service{};int draw_count{};uint32_t last_generation{};};
class RasterBackend final:public IDisplayBackend{
public:
 void present(const Scene&scene,const AssetPool&assets,bool full,const Rect*dirty,std::size_t count)override{
  ++draw_count_;last_full_=full;dirty_count_=count;last_target_dirty_=full;
  for(std::size_t i=0;i<count;i++)if(DisplayRasterizer::intersects(dirty[i],{20,20,1,1}))last_target_dirty_=true;
  uint16_t pixel=0;rasterizer_.render_strip(scene,&assets,{20,20,1,1},&pixel,1);last_pixel_=pixel;
 }
 uint8_t state()const override{return 1;}bool physical()const override{return true;}
 std::size_t draw_count()const{return draw_count_;}std::size_t dirty_count()const{return dirty_count_;}
 bool last_full()const{return last_full_;}bool last_target_dirty()const{return last_target_dirty_;}
 uint16_t last_pixel()const{return last_pixel_;}
private:DisplayRasterizer rasterizer_{};std::size_t draw_count_{},dirty_count_{};bool last_full_{},last_target_dirty_{};uint16_t last_pixel_{};
};
void upload_asset(DisplayRuntime&runtime,uint16_t transfer,uint16_t asset,const std::array<uint8_t,8>&pixels){
 std::array<uint8_t,56>out{};std::size_t n=0,outn=0;
 auto p=command(Opcode::AssetBegin,300,n);write_u16(p.data()+8,transfer);write_u16(p.data()+10,asset);p[12]=uint8_t(AssetFormat::Rgb565Raw);write_u16(p.data()+13,2);write_u16(p.data()+15,2);write_u32(p.data()+17,uint32_t(pixels.size()));write_u32(p.data()+21,crc32(pixels.data(),pixels.size()));n+=19;assert(send(runtime,p,n,out,outn)==Error::None);
 p=command(Opcode::AssetChunk,300,n);write_u16(p.data()+8,transfer);write_u32(p.data()+10,0);for(std::size_t i=0;i<pixels.size();i++)p[14+i]=pixels[i];n+=6+pixels.size();assert(send(runtime,p,n,out,outn)==Error::None);
 p=command(Opcode::AssetCommit,300,n);write_u16(p.data()+8,transfer);n+=2;assert(send(runtime,p,n,out,outn)==Error::None);
}}
int main(){NullDisplayBackend backend;DisplayRuntime runtime(backend,0x12345678);std::array<uint8_t,56>out{};std::size_t n=0,outn=0;
 auto p=command(Opcode::GetInfo,0,n);assert(send(runtime,p,n,out,outn)==Error::None);assert(outn==50&&out[0]==1&&out[2]==uint8_t(Opcode::GetInfo)&&read_u16(out.data()+8)==480&&read_u16(out.data()+10)==320&&read_u32(out.data()+46)==0x12345678);
 PhysicalBackend physical_backend;DisplayRuntime physical_runtime(physical_backend,7);p=command(Opcode::GetInfo,0,n);assert(send(physical_runtime,p,n,out,outn)==Error::None&&out[13]==1&&(out[14]&3)==3);
 TouchHit hit{};assert(!runtime.hit_test(10,10,TapGesture,hit));

 // ASSET-REPLACE-01 / COMPANION-PHYSICAL-SCENE-01.
 RasterBackend asset_backend;DisplayRuntime asset_runtime(asset_backend,11);std::array<uint8_t,56>asset_out{};std::size_t asset_n=0,asset_outn=0;
 auto asset_p=command(Opcode::BeginSync,300,asset_n);asset_p[asset_n++]=uint8_t(Mode::Dashboard);assert(send(asset_runtime,asset_p,asset_n,asset_out,asset_outn)==Error::None);
 asset_p=command(Opcode::DefineNode,300,asset_n);node_body(asset_p.data()+8,1,0,NodeKind::Group,0,0,480,320);asset_n+=34;assert(send(asset_runtime,asset_p,asset_n,asset_out,asset_outn)==Error::None);
 asset_p=command(Opcode::DefineNode,300,asset_n);node_body(asset_p.data()+8,2,1,NodeKind::Image,20,20,2,2);write_u16(asset_p.data()+36,0x8001);asset_n+=34;assert(send(asset_runtime,asset_p,asset_n,asset_out,asset_outn)==Error::None);
 asset_p=command(Opcode::CommitSync,300,asset_n);assert(send(asset_runtime,asset_p,asset_n,asset_out,asset_outn)==Error::None);asset_runtime.task(1);
 const uint32_t asset_scene_crc=asset_runtime.active_scene().crc32();const std::size_t initial_presents=asset_backend.draw_count();
 const std::array<uint8_t,8>asset_a{0x00,0xF8,0x00,0xF8,0x00,0xF8,0x00,0xF8};upload_asset(asset_runtime,1,0x8001,asset_a);asset_runtime.task(2);
 assert(asset_runtime.assets().find(0x8001)&&asset_backend.draw_count()==initial_presents+1&&asset_backend.dirty_count()==1&&asset_backend.last_target_dirty()&&!asset_backend.last_full()&&asset_backend.last_pixel()==0xF800);
 const std::array<uint8_t,8>asset_b{0xE0,0x07,0xE0,0x07,0xE0,0x07,0xE0,0x07};upload_asset(asset_runtime,2,0x8001,asset_b);asset_runtime.task(3);
 assert(asset_runtime.active_generation()==300&&asset_runtime.active_scene().crc32()==asset_scene_crc&&asset_backend.draw_count()==initial_presents+2&&asset_backend.dirty_count()==1&&asset_backend.last_target_dirty()&&!asset_backend.last_full()&&asset_backend.last_pixel()==0x07E0);
 p=command(Opcode::BeginSync,104,n);p[n++]=uint8_t(Mode::Dashboard);assert(send(runtime,p,n,out,outn)==Error::None&&runtime.active_generation()==0);
 p=command(Opcode::DefineNode,104,n);node_body(p.data()+8,1,0,NodeKind::Group,0,0,480,320);n+=34;assert(send(runtime,p,n,out,outn)==Error::None&&runtime.active_scene().node_count()==0);
 p=command(Opcode::DefineNode,104,n);node_body(p.data()+8,2,1,NodeKind::Circle,20,20,24,24,10);n+=34;assert(send(runtime,p,n,out,outn)==Error::None);
 p=command(Opcode::DefineNode,104,n);node_body(p.data()+8,3,1,NodeKind::Progress,20,60,100,8,11);write_u16(p.data()+38,200);n+=34;assert(send(runtime,p,n,out,outn)==Error::None);
 p=command(Opcode::DefineAnimation,104,n);write_u16(p.data()+8,1);write_u16(p.data()+10,1);p[12]=uint8_t(AnimationProperty::X);write_u16(p.data()+14,1000);write_u16(p.data()+16,0);write_u16(p.data()+18,0);n+=12;assert(send(runtime,p,n,out,outn)==Error::None);
 p=command(Opcode::DefineKeyframe,104,n);write_u16(p.data()+8,1);write_u16(p.data()+10,1000);write_u32(p.data()+12,300);p[16]=uint8_t(Easing::EaseInOut);n+=9;assert(send(runtime,p,n,out,outn)==Error::None);
 p=command(Opcode::DefineTouchRegion,104,n);write_u16(p.data()+8,7);write_i16(p.data()+10,0);write_i16(p.data()+12,0);write_i16(p.data()+14,100);write_i16(p.data()+16,100);write_i16(p.data()+18,1);p[20]=1;p[21]=1;p[22]=2;write_u32(p.data()+24,6);n+=20;assert(send(runtime,p,n,out,outn)==Error::None);
 p=command(Opcode::CommitSync,104,n);assert(send(runtime,p,n,out,outn)==Error::None&&runtime.active_generation()==104&&runtime.active_scene().node_count()==3&&!backend.last_full()&&runtime.active_scene().find_node(3)->progress==200);runtime.task(10);assert(backend.last_full());uint32_t scene_crc=runtime.active_scene().crc32();assert(scene_crc!=0);assert(runtime.hit_test(0,0,TapGesture,hit)&&hit.region_id==7&&hit.parameter==6);assert(runtime.hit_test(99,99,TapGesture,hit));assert(!runtime.hit_test(100,99,TapGesture,hit));assert(!runtime.hit_test(99,100,TapGesture,hit));
 p=command(Opcode::BeginUpdate,103,n);assert(send(runtime,p,n,out,outn)==Error::InvalidGeneration);
 p=command(Opcode::BeginUpdate,104,n);assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::PatchNode,104,n);write_u16(p.data()+8,2);p[10]=1;p[11]=2;write_i16(p.data()+12,30);n+=6;assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::CommitUpdate,104,n);assert(send(runtime,p,n,out,outn)==Error::None&&runtime.active_scene().crc32()!=scene_crc);runtime.task(10);assert(!backend.last_full()&&backend.dirty_count()==2);
 p=command(Opcode::BeginUpdate,104,n);assert(send(runtime,p,n,out,outn,100)==Error::None);p=command(Opcode::PatchNode,104,n);write_u16(p.data()+8,3);p[10]=13;p[11]=2;write_u16(p.data()+12,300);n+=6;assert(send(runtime,p,n,out,outn,100)==Error::None);p=command(Opcode::CommitUpdate,104,n);assert(send(runtime,p,n,out,outn,100)==Error::None&&runtime.active_scene().find_node(3)->progress==200);runtime.task(250);assert(runtime.active_scene().find_node(3)->progress==250);p=command(Opcode::BeginUpdate,104,n);assert(send(runtime,p,n,out,outn,250)==Error::None);p=command(Opcode::PatchNode,104,n);write_u16(p.data()+8,3);p[10]=13;p[11]=2;write_u16(p.data()+12,100);n+=6;assert(send(runtime,p,n,out,outn,250)==Error::None);p=command(Opcode::CommitUpdate,104,n);assert(send(runtime,p,n,out,outn,250)==Error::None);runtime.task(400);assert(runtime.active_scene().find_node(3)->progress==175);runtime.task(550);assert(runtime.active_scene().find_node(3)->progress==100);
 const uint8_t asset[]={1,2,3,4,5,6};p=command(Opcode::AssetBegin,104,n);write_u16(p.data()+8,3);write_u16(p.data()+10,9);p[12]=uint8_t(AssetFormat::Rgb565Raw);write_u16(p.data()+13,1);write_u16(p.data()+15,3);write_u32(p.data()+17,sizeof(asset));write_u32(p.data()+21,crc32(asset,sizeof(asset)));n+=19;assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::AssetChunk,104,n);write_u16(p.data()+8,3);write_u32(p.data()+10,0);for(std::size_t i=0;i<sizeof(asset);i++)p[14+i]=asset[i];n+=6+sizeof(asset);assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::AssetCommit,104,n);write_u16(p.data()+8,3);n+=2;assert(send(runtime,p,n,out,outn)==Error::None&&runtime.assets().bytes_used()==sizeof(asset));
 p=command(Opcode::AssetRelease,104,n);write_u16(p.data()+8,9);n+=2;assert(send(runtime,p,n,out,outn)==Error::None&&runtime.assets().bytes_used()==0);
 p=command(Opcode::Heartbeat,104,n);assert(send(runtime,p,n,out,outn,100)==Error::None&&runtime.host_online());runtime.task(5101);assert(!runtime.host_online());
 std::array<uint8_t,56>event{};std::size_t eventn=0;uint32_t trace=0;assert(runtime.inject_touch(7,1,22,33,99,trace,event.data(),eventn)&&trace==1&&eventn==24&&event[2]==uint8_t(Opcode::TouchEvent)&&read_u32(event.data()+8)==trace&&read_u16(event.data()+12)==7);for(uint32_t expected=2;expected<=20;expected++){assert(runtime.inject_touch(7,1,22,33,99,trace,event.data(),eventn)&&trace==expected&&read_u32(event.data()+8)==expected);}
 p=command(static_cast<Opcode>(0x7F),104,n);assert(send(runtime,p,n,out,outn)==Error::UnsupportedOpcode&&(out[3]&ResponseError));
 p=command(Opcode::BeginSync,105,n);p[n++]=uint8_t(Mode::Dashboard);assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::DefineTouchRegion,105,n);write_u16(p.data()+8,8);write_i16(p.data()+10,200);write_i16(p.data()+12,200);write_i16(p.data()+14,50);write_i16(p.data()+16,50);write_i16(p.data()+18,2);p[20]=1;p[21]=1;p[22]=1;write_u32(p.data()+24,8);n+=20;assert(send(runtime,p,n,out,outn)==Error::None);assert(runtime.hit_test(10,10,TapGesture,hit)&&hit.region_id==7);assert(!runtime.hit_test(210,210,TapGesture,hit));p=command(Opcode::CancelSync,105,n);assert(send(runtime,p,n,out,outn)==Error::None&&runtime.active_generation()==104);
 p=command(Opcode::BeginSync,106,n);p[n++]=uint8_t(Mode::Dashboard);assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::DefineNode,106,n);node_body(p.data()+8,1,0,NodeKind::Group,0,0,480,320);n+=34;assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::DefineNode,106,n);node_body(p.data()+8,3,1,NodeKind::Progress,20,60,100,8);write_u16(p.data()+38,700);n+=34;assert(send(runtime,p,n,out,outn)==Error::None);p=command(Opcode::CommitSync,106,n);assert(send(runtime,p,n,out,outn)==Error::None&&runtime.active_scene().find_node(3)->progress==700&&!runtime.active_scene().find_node(3)->progress_transition);assert(runtime.active_scene().region_count()==0&&!runtime.hit_test(10,10,TapGesture,hit));

 SlowBackend slow_backend;DisplayRuntime slow_runtime(slow_backend,9);
 p=command(Opcode::BeginSync,200,n);p[n++]=uint8_t(Mode::Dashboard);assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::DefineNode,200,n);node_body(p.data()+8,1,0,NodeKind::Group,0,0,480,320);n+=34;assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::CommitSync,200,n);auto started=std::chrono::steady_clock::now();assert(send(slow_runtime,p,n,out,outn)==Error::None);auto elapsed=std::chrono::steady_clock::now()-started;assert(elapsed<std::chrono::milliseconds(50)&&slow_backend.draw_count==0);
 p=command(Opcode::BeginSync,201,n);p[n++]=uint8_t(Mode::Dashboard);assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::DefineNode,201,n);node_body(p.data()+8,1,0,NodeKind::Group,0,0,480,320);n+=34;assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::DefineNode,201,n);node_body(p.data()+8,2,1,NodeKind::Rectangle,10,10,40,40);n+=34;assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::DefineTouchRegion,201,n);write_u16(p.data()+8,9);write_i16(p.data()+10,0);write_i16(p.data()+12,0);write_i16(p.data()+14,100);write_i16(p.data()+16,100);write_i16(p.data()+18,1);p[20]=1;p[21]=1;p[22]=2;write_u32(p.data()+24,11);n+=20;assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::CommitSync,201,n);started=std::chrono::steady_clock::now();assert(send(slow_runtime,p,n,out,outn)==Error::None);elapsed=std::chrono::steady_clock::now()-started;assert(elapsed<std::chrono::milliseconds(50)&&slow_backend.draw_count==0&&slow_runtime.active_generation()==201);assert(slow_runtime.hit_test(20,20,TapGesture,hit)&&hit.region_id==9);assert(slow_runtime.inject_touch(9,1,20,20,12,trace,event.data(),eventn));
 slow_backend.service=[&]{p=command(Opcode::BeginUpdate,201,n);assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::PatchNode,201,n);write_u16(p.data()+8,2);p[10]=1;p[11]=2;write_i16(p.data()+12,30);n+=6;assert(send(slow_runtime,p,n,out,outn)==Error::None);p=command(Opcode::CommitUpdate,201,n);const auto ack_started=std::chrono::steady_clock::now();assert(send(slow_runtime,p,n,out,outn)==Error::None);assert(std::chrono::steady_clock::now()-ack_started<std::chrono::milliseconds(50));assert(slow_runtime.inject_touch(9,1,30,20,13,trace,event.data(),eventn));};
 started=std::chrono::steady_clock::now();slow_runtime.task(20);elapsed=std::chrono::steady_clock::now()-started;assert(elapsed>=std::chrono::milliseconds(280)&&slow_backend.draw_count==1&&slow_backend.last_generation==201&&slow_runtime.active_scene().find_node(2)->bounds.x==30);started=std::chrono::steady_clock::now();slow_runtime.task(30);elapsed=std::chrono::steady_clock::now()-started;assert(elapsed>=std::chrono::milliseconds(280)&&slow_backend.draw_count==2&&slow_backend.last_generation==201);

 Scene policies;policies.clear(1);TouchRegion pass{};pass.id=1;pass.bounds={0,0,100,100};pass.priority=50;pass.gestures=TapGesture;pass.action=uint8_t(TouchActionKind::LocalControl);pass.flags=uint8_t(TouchMode::PassThrough);pass.parameter=1;assert(policies.define_region(pass)==Error::None);TouchRegion capture=pass;capture.id=2;capture.priority=10;capture.flags=uint8_t(TouchMode::Capture);capture.parameter=2;assert(policies.define_region(capture)==Error::None);assert(policies.hit_test(50,50,TapGesture,hit)&&hit.region_id==2);TouchRegion higher=capture;higher.id=3;higher.priority=20;higher.parameter=3;assert(policies.define_region(higher)==Error::None);assert(policies.hit_test(50,50,TapGesture,hit)&&hit.region_id==3);TouchRegion tie=higher;tie.id=4;tie.parameter=4;assert(policies.define_region(tie)==Error::None);assert(policies.hit_test(50,50,TapGesture,hit)&&hit.region_id==4);TouchRegion ignored=tie;ignored.id=5;ignored.priority=30;ignored.flags=uint8_t(TouchMode::Ignore);assert(policies.define_region(ignored)==Error::None);assert(!policies.hit_test(50,50,TapGesture,hit));assert(!policies.hit_test(101,50,TapGesture,hit));
}
