using System.Text;
using StreamDeckDIY.Protocol.DisplayLink;
namespace StreamDeckDIY.Core.DisplayLink;
public static class DisplayLinkCommandEncoder
{
 public static byte[] BeginSync(DisplayMode mode)=>[(byte)mode];
 public static byte[] DefineNode(DisplayNode n){var b=new byte[34];DisplayLinkCodec.WriteU16(b,0,n.Id);DisplayLinkCodec.WriteU16(b,2,n.ParentId);b[4]=(byte)n.Kind;b[5]=(byte)(n.Visible?1:0);DisplayLinkCodec.WriteI16(b,6,n.ZIndex);Bounds(b,8,n.Bounds);DisplayLinkCodec.WriteU16(b,16,n.FillColor);DisplayLinkCodec.WriteU16(b,18,n.StrokeColor);b[20]=n.StrokeWidth;b[21]=n.CornerRadius;b[22]=n.Opacity;b[23]=n.FontId;b[24]=n.FontSize;b[25]=n.Alignment;DisplayLinkCodec.WriteU16(b,26,n.IconId);DisplayLinkCodec.WriteU16(b,28,n.AssetId);DisplayLinkCodec.WriteU16(b,30,n.ProgressValue);DisplayLinkCodec.WriteI16(b,32,n.Rotation);return b;}
 public static byte[] PatchNode(DisplayNode n,DisplayNode old){var b=new List<byte>(40);void U8(byte p,byte v){b.Add(p);b.Add(1);b.Add(v);}void I16(byte p,short v){b.Add(p);b.Add(2);b.Add((byte)v);b.Add((byte)(v>>8));}void U16(byte p,ushort v)=>I16(p,(short)v);if(n.Bounds.X!=old.Bounds.X)I16(1,n.Bounds.X);if(n.Bounds.Y!=old.Bounds.Y)I16(2,n.Bounds.Y);if(n.Bounds.Width!=old.Bounds.Width)I16(3,n.Bounds.Width);if(n.Bounds.Height!=old.Bounds.Height)I16(4,n.Bounds.Height);if(n.Visible!=old.Visible)U8(5,(byte)(n.Visible?1:0));if(n.Opacity!=old.Opacity)U8(6,n.Opacity);if(n.FillColor!=old.FillColor)U16(7,n.FillColor);if(n.StrokeColor!=old.StrokeColor)U16(8,n.StrokeColor);if(n.StrokeWidth!=old.StrokeWidth)U8(9,n.StrokeWidth);if(n.CornerRadius!=old.CornerRadius)U8(10,n.CornerRadius);if(n.IconId!=old.IconId)U16(11,n.IconId);if(n.AssetId!=old.AssetId)U16(12,n.AssetId);if(n.ProgressValue!=old.ProgressValue)U16(13,n.ProgressValue);if(n.Rotation!=old.Rotation)I16(14,n.Rotation);var r=new byte[b.Count+2];DisplayLinkCodec.WriteU16(r,0,n.Id);b.CopyTo(r,2);return r;}
 public static IEnumerable<byte[]> StringFragments(ushort nodeId,string text){var utf8=Encoding.UTF8.GetBytes(text);const int chunk=42;for(var offset=0;offset<utf8.Length||offset==0;){var count=Math.Min(chunk,utf8.Length-offset);while(count>0&&offset+count<utf8.Length&&(utf8[offset+count]&0xC0)==0x80)count--;var b=new byte[6+count];DisplayLinkCodec.WriteU16(b,0,nodeId);DisplayLinkCodec.WriteU16(b,2,(ushort)offset);DisplayLinkCodec.WriteU16(b,4,checked((ushort)utf8.Length));utf8.AsSpan(offset,count).CopyTo(b.AsSpan(6));yield return b;if(utf8.Length==0)yield break;offset+=count;}}
 public static byte[] DefineTouch(DisplayTouchRegion r){var b=new byte[20];DisplayLinkCodec.WriteU16(b,0,r.Id);Bounds(b,2,r.Bounds);DisplayLinkCodec.WriteI16(b,10,r.Priority);b[12]=(byte)r.Gestures;b[13]=(byte)r.ActionKind;b[14]=(byte)r.Mode;DisplayLinkCodec.WriteU32(b,16,r.ActionParameter);return b;}
 public static byte[] DefineAnimation(DisplayGraphAnimation a){var b=new byte[12];DisplayLinkCodec.WriteU16(b,0,a.Id);DisplayLinkCodec.WriteU16(b,2,a.TargetNodeId);b[4]=(byte)a.Property;b[5]=(byte)(a.Loop?1:0);DisplayLinkCodec.WriteU16(b,6,a.DurationMilliseconds);DisplayLinkCodec.WriteU16(b,8,a.DelayMilliseconds);DisplayLinkCodec.WriteU16(b,10,a.RepeatCount);return b;}
 public static byte[] DefineKeyframe(ushort id,DisplayKeyframe k){var b=new byte[9];DisplayLinkCodec.WriteU16(b,0,id);DisplayLinkCodec.WriteU16(b,2,k.TimeMilliseconds);DisplayLinkCodec.WriteU32(b,4,unchecked((uint)k.Value));b[8]=(byte)k.Easing;return b;}
 public static byte[] Id(ushort id){var b=new byte[2];DisplayLinkCodec.WriteU16(b,0,id);return b;}
 private static void Bounds(Span<byte>b,int o,DisplayBounds r){DisplayLinkCodec.WriteI16(b,o,r.X);DisplayLinkCodec.WriteI16(b,o+2,r.Y);DisplayLinkCodec.WriteI16(b,o+4,r.Width);DisplayLinkCodec.WriteI16(b,o+6,r.Height);}
}
