#include "display/display_scene.hpp"
#include <algorithm>
#include <cstring>
namespace streamdeck::display {
namespace { constexpr uint32_t PROGRESS_TRANSITION_MS=300;uint32_t crc_byte(uint32_t c,uint8_t b){c^=b;for(int i=0;i<8;i++)c=(c>>1)^(0xEDB88320u&uint32_t(0-int(c&1)));return c;}void advance_progress(Node&n,uint32_t now){if(!n.progress_transition)return;const uint32_t elapsed=now-n.progress_started_ms;if(elapsed>=PROGRESS_TRANSITION_MS){n.progress=n.progress_target;n.progress_transition=false;return;}const int32_t delta=int32_t(n.progress_target)-n.progress_start;n.progress=uint16_t(int32_t(n.progress_start)+(delta*int32_t(elapsed))/int32_t(PROGRESS_TRANSITION_MS));}}
void Scene::clear(uint32_t g,Mode m){nodes_={};regions_={};animations_={};strings_={};string_used_=0;generation=g;mode=m;}
bool Scene::valid_bounds(const Rect&r)const{return r.width>=0&&r.height>=0&&r.x>=0&&r.y>=0&&int32_t(r.x)+r.width<=480&&int32_t(r.y)+r.height<=320;}
Node* Scene::find_node(uint16_t id){for(auto&n:nodes_)if(n.used&&n.id==id)return &n;return nullptr;} const Node* Scene::find_node(uint16_t id)const{for(const auto&n:nodes_)if(n.used&&n.id==id)return &n;return nullptr;}
bool Scene::text(const Node&n,const uint8_t*&data,std::size_t&length)const{if(!n.used||n.kind!=NodeKind::Text||n.text_offset+n.text_length>strings_.size()){data=nullptr;length=0;return false;}data=strings_.data()+n.text_offset;length=n.text_length;return true;}
Rect Scene::absolute_bounds(const Node&n)const{const Node*chain[9]{};std::size_t depth=0;const Node*current=&n;while(current&&depth<9){chain[depth++]=current;current=current->parent?find_node(current->parent):nullptr;}int32_t x=0,y=0,sx=1000,sy=1000;for(std::size_t i=depth;i-->0;){const Node&part=*chain[i];x+=(int32_t(part.bounds.x)*sx)/1000;y+=(int32_t(part.bounds.y)*sy)/1000;sx=(sx*part.scale_x)/1000;sy=(sy*part.scale_y)/1000;}return{int16_t(x),int16_t(y),int16_t((int32_t(n.bounds.width)*sx)/1000),int16_t((int32_t(n.bounds.height)*sy)/1000)};}
bool Scene::parent_valid(uint16_t id,uint16_t parent)const{if(parent==0)return true;const Node*p=find_node(parent);if(!p||p->kind!=NodeKind::Group)return false;for(unsigned i=0;i<MAX_NODES&&parent;i++){if(parent==id)return false;const Node*n=find_node(parent);parent=n?n->parent:0;}return parent==0;}
Error Scene::define_node(const Node& in){if(in.id==0||find_node(in.id))return Error::InvalidNode;if(uint8_t(in.kind)>uint8_t(NodeKind::Line))return Error::UnsupportedPrimitive;if(!valid_bounds(in.bounds))return Error::OutOfBounds;if(!parent_valid(in.id,in.parent))return Error::InvalidParent;for(auto&n:nodes_)if(!n.used){n=in;if(n.kind==NodeKind::Progress){n.progress=std::min<uint16_t>(n.progress,1000);n.progress_start=n.progress;n.progress_target=n.progress;n.progress_transition=false;}n.used=true;return Error::None;}return Error::TooManyNodes;}
Error Scene::patch_node(uint16_t id,const uint8_t*d,std::size_t len,uint32_t now){Node*n=find_node(id);if(!n)return Error::InvalidNode;advance_progress(*n,now);Node candidate=*n;std::size_t p=0;while(p<len){if(p+2>len)return Error::InvalidString;uint8_t prop=d[p++],size=d[p++];if(p+size>len)return Error::InvalidString;switch(prop){case 1:if(size!=2)return Error::UnsupportedProperty;candidate.bounds.x=read_i16(d+p);break;case 2:if(size!=2)return Error::UnsupportedProperty;candidate.bounds.y=read_i16(d+p);break;case 3:if(size!=2)return Error::UnsupportedProperty;candidate.bounds.width=read_i16(d+p);break;case 4:if(size!=2)return Error::UnsupportedProperty;candidate.bounds.height=read_i16(d+p);break;case 5:if(size!=1)return Error::UnsupportedProperty;candidate.flags=(candidate.flags&~1u)|(d[p]?1u:0u);break;case 6:if(size!=1)return Error::UnsupportedProperty;candidate.opacity=d[p];break;case 7:if(size!=2)return Error::UnsupportedProperty;candidate.fill=read_u16(d+p);break;case 8:if(size!=2)return Error::UnsupportedProperty;candidate.stroke=read_u16(d+p);break;case 9:if(size!=1)return Error::UnsupportedProperty;candidate.stroke_width=d[p];break;case 10:if(size!=1)return Error::UnsupportedProperty;candidate.corner_radius=d[p];break;case 11:if(size!=2)return Error::UnsupportedProperty;candidate.icon_id=read_u16(d+p);break;case 12:if(size!=2)return Error::UnsupportedProperty;candidate.asset_id=read_u16(d+p);break;case 13:{if(size!=2)return Error::UnsupportedProperty;const uint16_t target=std::min<uint16_t>(read_u16(d+p),1000);if(candidate.kind==NodeKind::Progress){candidate.progress_start=candidate.progress;candidate.progress_target=target;candidate.progress_started_ms=now;candidate.progress_transition=target!=candidate.progress;}else candidate.progress=target;break;}case 14:if(size!=2)return Error::UnsupportedProperty;candidate.rotation=read_i16(d+p);break;default:return Error::UnsupportedProperty;}p+=size;}if(!valid_bounds(candidate.bounds))return Error::OutOfBounds;*n=candidate;return Error::None;}
Error Scene::delete_node(uint16_t id){Node*n=find_node(id);if(!n)return Error::InvalidNode;for(const auto&v:nodes_)if(v.used&&v.parent==id)return Error::InvalidParent;*n={};return Error::None;}
Error Scene::set_string(uint16_t id,uint16_t offset,uint16_t total,const uint8_t*d,std::size_t len){Node*n=find_node(id);if(!n||n->kind!=NodeKind::Text)return Error::InvalidNode;if(total>MAX_STRING_BYTES||offset+len>total)return Error::InvalidString;if(offset==0){compact_strings(id);n=find_node(id);if(string_used_+total>MAX_STRING_BYTES)return Error::NoMemory;n->text_offset=string_used_;n->text_length=total;string_used_=uint16_t(string_used_+total);}if(n->text_length!=total||n->text_offset+offset+len>MAX_STRING_BYTES)return Error::InvalidString;std::memcpy(strings_.data()+n->text_offset+offset,d,len);return Error::None;}
void Scene::compact_strings(uint16_t excluded){uint16_t next=0;for(auto&n:nodes_){if(!n.used||n.kind!=NodeKind::Text||n.id==excluded||n.text_length==0)continue;if(n.text_offset!=next)std::memmove(strings_.data()+next,strings_.data()+n.text_offset,n.text_length);n.text_offset=next;next=uint16_t(next+n.text_length);}if(Node*n=find_node(excluded)){n->text_offset=0;n->text_length=0;}string_used_=next;}
Error Scene::define_region(const TouchRegion&r){if(r.id==0||r.bounds.width<=0||r.bounds.height<=0||!valid_bounds(r.bounds)||r.action>uint8_t(TouchActionKind::HostInteraction)||r.flags<uint8_t(TouchMode::Capture)||r.flags>uint8_t(TouchMode::Ignore))return Error::InvalidRegion;for(auto&v:regions_)if(v.used&&v.id==r.id){v=r;v.used=true;return Error::None;}for(auto&v:regions_)if(!v.used){v=r;v.used=true;return Error::None;}return Error::TooManyRegions;}
Error Scene::delete_region(uint16_t id){for(auto&r:regions_)if(r.used&&r.id==id){r={};return Error::None;}return Error::InvalidRegion;}
bool Scene::hit_test(int16_t x,int16_t y,uint8_t gesture,TouchHit&result)const{const TouchRegion*blocking=nullptr;const TouchRegion*passing=nullptr;auto higher=[](const TouchRegion&candidate,const TouchRegion*current){return current==nullptr||candidate.priority>current->priority||(candidate.priority==current->priority&&candidate.id>current->id);};for(const auto&region:regions_){if(!region.used||(region.gestures&gesture)==0)continue;const Rect&b=region.bounds;if(x<b.x||y<b.y||x>=int32_t(b.x)+b.width||y>=int32_t(b.y)+b.height)continue;const TouchMode mode=static_cast<TouchMode>(region.flags);if(mode==TouchMode::PassThrough){if(higher(region,passing))passing=&region;}else if(higher(region,blocking))blocking=&region;}const TouchRegion*selected=blocking; if(selected&&static_cast<TouchMode>(selected->flags)==TouchMode::Ignore)return false;if(selected==nullptr)selected=passing;if(selected==nullptr||selected->action==uint8_t(TouchActionKind::None))return false;result={selected->id,selected->action,selected->parameter,static_cast<TouchMode>(selected->flags)};return true;}
Error Scene::define_animation(const Animation&a){if(a.id==0||!find_node(a.target)||uint8_t(a.property)>6)return Error::InvalidAnimation;for(auto&v:animations_)if(v.used&&v.id==a.id){v=a;v.used=true;return Error::None;}for(auto&v:animations_)if(!v.used){v=a;v.used=true;return Error::None;}return Error::TooManyAnimations;}
Error Scene::define_keyframe(uint16_t id,const Keyframe&k){for(auto&a:animations_)if(a.used&&a.id==id){if(a.keyframe_count>=MAX_KEYFRAMES)return Error::InvalidAnimation;a.keyframes[a.keyframe_count]=k;a.keyframes[a.keyframe_count++].used=true;return Error::None;}return Error::InvalidAnimation;}
Error Scene::play_animation(uint16_t id,bool play,uint32_t now){for(auto&a:animations_)if(a.used&&a.id==id){a.playing=play;a.start_ms=now;if(Node*n=find_node(a.target))switch(a.property){case AnimationProperty::X:a.base_value=n->bounds.x;break;case AnimationProperty::Y:a.base_value=n->bounds.y;break;case AnimationProperty::Opacity:a.base_value=n->opacity;break;case AnimationProperty::ScaleX:a.base_value=n->scale_x;break;case AnimationProperty::ScaleY:a.base_value=n->scale_y;break;case AnimationProperty::Rotation:a.base_value=n->rotation;break;}return Error::None;}return Error::InvalidAnimation;}
void Scene::tick_animations(uint32_t now,Rect*dirty,std::size_t&count,std::size_t capacity){for(auto&a:animations_){if(!a.used||!a.playing||a.keyframe_count==0||a.duration_ms==0)continue;const uint32_t elapsed=now-a.start_ms;if(elapsed<a.delay_ms)continue;uint32_t local=elapsed-a.delay_ms;const uint32_t cycles=local/a.duration_ms;if(!(a.flags&1u)&&cycles>a.repeat){local=a.duration_ms;a.playing=false;}else local%=a.duration_ms;const Keyframe*left=&a.keyframes[0],*right=left;for(uint8_t i=1;i<a.keyframe_count;i++){right=&a.keyframes[i];if(local<=right->time_ms)break;left=right;}int32_t value=left->value;if(right!=left&&right->time_ms>left->time_ms){uint32_t q=uint32_t((uint64_t(local-left->time_ms)*65536u)/(right->time_ms-left->time_ms));switch(right->easing){case Easing::EaseIn:q=uint32_t((uint64_t(q)*q)>>16);break;case Easing::EaseOut:q=65536u-uint32_t((uint64_t(65536u-q)*(65536u-q))>>16);break;case Easing::EaseInOut:q=q<32768u?uint32_t((2ull*q*q)>>16):65536u-uint32_t((2ull*(65536u-q)*(65536u-q))>>16);break;case Easing::Step:q=0;break;default:break;}value=left->value+int32_t((int64_t(right->value-left->value)*q)>>16);}Node*n=find_node(a.target);if(!n)continue;Rect old=absolute_bounds(*n);switch(a.property){case AnimationProperty::X:n->bounds.x=int16_t(value);break;case AnimationProperty::Y:n->bounds.y=int16_t(value);break;case AnimationProperty::Opacity:n->opacity=uint8_t(std::clamp<int32_t>(value,0,255));break;case AnimationProperty::ScaleX:n->scale_x=int16_t(value);break;case AnimationProperty::ScaleY:n->scale_y=int16_t(value);break;case AnimationProperty::Rotation:n->rotation=int16_t(value);break;}if(count<capacity)dirty[count++]=old;if(count<capacity)dirty[count++]=absolute_bounds(*n);}}
void Scene::tick_progress(uint32_t now,Rect*dirty,std::size_t&count,std::size_t capacity){for(auto&n:nodes_){if(!n.used||n.kind!=NodeKind::Progress||!n.progress_transition)continue;const uint16_t old=n.progress;advance_progress(n,now);if(n.progress==old)continue;if(count<capacity)dirty[count++]=absolute_bounds(n);}}
Error Scene::delete_animation(uint16_t id){for(auto&a:animations_)if(a.used&&a.id==id){a={};return Error::None;}return Error::InvalidAnimation;}
std::size_t Scene::node_count()const{return std::count_if(nodes_.begin(),nodes_.end(),[](const Node&n){return n.used;});}std::size_t Scene::region_count()const{return std::count_if(regions_.begin(),regions_.end(),[](const TouchRegion&r){return r.used;});}std::size_t Scene::animation_count()const{return std::count_if(animations_.begin(),animations_.end(),[](const Animation&a){return a.used;});}
uint32_t Scene::crc32()const{uint32_t c=0xFFFFFFFFu;auto add=[&](uint32_t v){for(int i=0;i<4;i++)c=crc_byte(c,uint8_t(v>>(i*8)));};add(generation);add(uint8_t(mode));for(const auto&n:nodes_)if(n.used){add(n.id);add(n.parent);add(uint8_t(n.kind));add(uint16_t(n.bounds.x));add(uint16_t(n.bounds.y));add(uint16_t(n.bounds.width));add(uint16_t(n.bounds.height));add(n.z);add(n.fill);add(n.asset_id);add(n.kind==NodeKind::Progress?n.progress_target:n.progress);}for(const auto&r:regions_)if(r.used){add(r.id);add(uint16_t(r.bounds.x));add(uint16_t(r.bounds.y));add(uint16_t(r.bounds.width));add(uint16_t(r.bounds.height));add(uint16_t(r.priority));add(r.gestures);add(r.action);add(r.flags);add(r.parameter);}return c^0xFFFFFFFFu;}
}
