#pragma once

enum {
    REPORT_ID_KEYBOARD = 1,
    REPORT_ID_CONSUMER_CONTROL,
};

enum {
    HID_INSTANCE_INPUT = 0,
    HID_INSTANCE_CONTROL,
    HID_INSTANCE_COUNT,
};

#define STREAMDECK_CONTROL_REPORT_SIZE 64
