using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows.Input;
using Microsoft.UI.Xaml;
using StreamDeckDIY.App.Services;
using StreamDeckDIY.Core.Audio;
using StreamDeckDIY.Core.HostActions;

namespace StreamDeckDIY.App.ViewModels;

public sealed class HostActionLibraryViewModel : ObservableObject, IAsyncDisposable
{
    private readonly IHostActionRegistry registry;
    private readonly IHostActionInteraction interaction;
    private readonly IAudioOutputService audioOutputService;
    private HostActionDefinition? selectedAction;
    private string name = string.Empty;
    private HostActionKindOption selectedKindOption;
    private string target = string.Empty;
    private string feedback = string.Empty;
    private string validationMessage = string.Empty;
    private bool nameWasAutoGenerated;
    private AudioOutputDevice? selectedPrimaryAudioDevice;
    private AudioOutputDevice? selectedSecondaryAudioDevice;
    private readonly object autosaveSync = new();
    private readonly SemaphoreSlim saveGate = new(1, 1);
    private CancellationTokenSource? debounce;
    private Task pendingTask = Task.CompletedTask;
    private HostActionDraft? pendingDraft;
    private uint? editingActionId;
    private long editorSession;
    private long revision;
    private bool loadingEditor;
    private bool disposed;

    public HostActionLibraryViewModel(
        IHostActionRegistry registry,
        IHostActionInteraction interaction,
        IAudioOutputService audioOutputService)
    {
        this.registry = registry;
        this.interaction = interaction;
        this.audioOutputService = audioOutputService;
        KindOptions =
        [
            new("Aplicación", HostActionKind.LaunchApplication),
            new("URL", HostActionKind.OpenUrl),
            new("Macro", HostActionKind.Macro),
            new("Salida de audio", HostActionKind.SetAudioOutput),
            new("Alternar salida de audio", HostActionKind.ToggleAudioOutput),
        ];
        selectedKindOption = KindOptions[0];
        NewCommand = new AsyncRelayCommand(_ => NewAsync());
        NewMacroCommand = new AsyncRelayCommand(_ => NewMacroAsync());
        DeleteCommand = new AsyncRelayCommand(_ => DeleteAsync());
        BrowseCommand = new AsyncRelayCommand(_ => BrowseAsync());
        AddActionStepCommand = new AsyncRelayCommand(_ => AddActionStepAsync());
        AddDelayStepCommand = new AsyncRelayCommand(_ => AddDelayStepAsync());
        RefreshAudioDevicesCommand = new AsyncRelayCommand(
            _ => RefreshAudioDevicesAsync());
    }

    public event EventHandler? ActionsChanged;
    public ObservableCollection<HostActionDefinition> Actions { get; } = [];
    public ObservableCollection<HostActionDefinition> Macros { get; } = [];
    public ObservableCollection<HostActionDefinition> MacroActionOptions { get; } = [];
    public ObservableCollection<MacroStepEditorViewModel> MacroSteps { get; } = [];
    public ObservableCollection<AudioOutputDevice> AudioDevices { get; } = [];
    public Visibility ActionsEmptyVisibility => Actions.Count == 0
        ? Visibility.Visible : Visibility.Collapsed;
    public Visibility MacrosEmptyVisibility => Macros.Count == 0
        ? Visibility.Visible : Visibility.Collapsed;
    public IReadOnlyList<HostActionKindOption> KindOptions { get; }
    public ICommand NewCommand { get; }
    public ICommand NewMacroCommand { get; }
    public ICommand DeleteCommand { get; }
    public ICommand BrowseCommand { get; }
    public ICommand AddActionStepCommand { get; }
    public ICommand AddDelayStepCommand { get; }
    public ICommand RefreshAudioDevicesCommand { get; }

    public HostActionDefinition? SelectedAction
    {
        get => selectedAction;
        set
        {
            if (value is null || ReferenceEquals(selectedAction, value)) return;
            selectedAction = value;
            OnPropertyChanged();
            editorSession++;
            editingActionId = value.Id;
            loadingEditor = true;
            try
            {
                Name = value.Name;
                SelectedKindOption = KindOptions.First(option => option.Kind == value.Kind);
                Target = value.Target ?? string.Empty;
                LoadMacroSteps(value.Steps);
                LoadAudioSelection(value.AudioOutput);
                nameWasAutoGenerated = false;
                UpdateValidation();
                Feedback = "Edición con guardado automático.";
            }
            finally { loadingEditor = false; }
        }
    }

    public string Name
    {
        get => name;
        set
        {
            if (!SetProperty(ref name, value)) return;
            nameWasAutoGenerated = false;
            EditorChanged();
        }
    }

    public HostActionKindOption SelectedKindOption
    {
        get => selectedKindOption;
        set
        {
            if (!SetProperty(ref selectedKindOption, value)) return;
            OnPropertyChanged(nameof(TargetLabel));
            OnPropertyChanged(nameof(ApplicationEditorVisibility));
            OnPropertyChanged(nameof(TargetEditorVisibility));
            OnPropertyChanged(nameof(MacroEditorVisibility));
            OnPropertyChanged(nameof(AudioEditorVisibility));
            OnPropertyChanged(nameof(SecondaryAudioVisibility));
            OnPropertyChanged(nameof(PrimaryAudioLabel));
            EditorChanged();
        }
    }

    public string Target
    {
        get => target;
        set { if (SetProperty(ref target, value)) EditorChanged(); }
    }

    public string TargetLabel => SelectedKindOption.Kind == HostActionKind.LaunchApplication
        ? "Ruta del ejecutable" : "URL (http/https)";
    public Visibility ApplicationEditorVisibility =>
        SelectedKindOption.Kind == HostActionKind.LaunchApplication
            ? Visibility.Visible : Visibility.Collapsed;
    public Visibility TargetEditorVisibility =>
        SelectedKindOption.Kind is HostActionKind.Macro or
            HostActionKind.SetAudioOutput or HostActionKind.ToggleAudioOutput
            ? Visibility.Collapsed : Visibility.Visible;
    public Visibility MacroEditorVisibility =>
        SelectedKindOption.Kind == HostActionKind.Macro
            ? Visibility.Visible : Visibility.Collapsed;
    public Visibility AudioEditorVisibility =>
        SelectedKindOption.Kind is HostActionKind.SetAudioOutput or
            HostActionKind.ToggleAudioOutput
            ? Visibility.Visible : Visibility.Collapsed;
    public Visibility SecondaryAudioVisibility =>
        SelectedKindOption.Kind == HostActionKind.ToggleAudioOutput
            ? Visibility.Visible : Visibility.Collapsed;
    public string PrimaryAudioLabel =>
        SelectedKindOption.Kind == HostActionKind.ToggleAudioOutput
            ? "Dispositivo A" : "Dispositivo";
    public AudioOutputDevice? SelectedPrimaryAudioDevice
    {
        get => selectedPrimaryAudioDevice;
        set { if (SetProperty(ref selectedPrimaryAudioDevice, value)) EditorChanged(); }
    }
    public AudioOutputDevice? SelectedSecondaryAudioDevice
    {
        get => selectedSecondaryAudioDevice;
        set { if (SetProperty(ref selectedSecondaryAudioDevice, value)) EditorChanged(); }
    }
    public string Feedback { get => feedback; private set => SetProperty(ref feedback, value); }
    public string ValidationMessage
    {
        get => validationMessage;
        private set => SetProperty(ref validationMessage, value);
    }

    public async Task InitializeAsync(CancellationToken cancellationToken = default)
    {
        await registry.InitializeAsync(cancellationToken);
        await RefreshAudioDevicesAsync(cancellationToken);
        Refresh();
    }

    private Task NewAsync()
    {
        editorSession++;
        editingActionId = null;
        selectedAction = null;
        OnPropertyChanged(nameof(SelectedAction));
        loadingEditor = true;
        try
        {
            Name = string.Empty;
            SelectedKindOption = KindOptions[0];
            Target = string.Empty;
            ClearMacroSteps();
            SelectedPrimaryAudioDevice = null;
            SelectedSecondaryAudioDevice = null;
            Feedback = "Nueva acción. Se guardará automáticamente cuando sea válida.";
            nameWasAutoGenerated = false;
            UpdateValidation();
        }
        finally { loadingEditor = false; }
        return Task.CompletedTask;
    }

    private async Task NewMacroAsync()
    {
        await NewAsync();
        SelectedKindOption = KindOptions.First(option => option.Kind == HostActionKind.Macro);
        Feedback = "Nueva macro.";
    }

    private async Task BrowseAsync()
    {
        if (SelectedKindOption.Kind != HostActionKind.LaunchApplication) return;
        var selectedPath = await interaction.PickExecutableAsync();
        if (string.IsNullOrWhiteSpace(selectedPath)) return;
        var shouldSuggestName = string.IsNullOrWhiteSpace(Name) || nameWasAutoGenerated;
        Target = selectedPath;
        if (shouldSuggestName)
        {
            name = HostActionNameSuggester.FromExecutable(selectedPath);
            OnPropertyChanged(nameof(Name));
            nameWasAutoGenerated = true;
        }
        EditorChanged();
    }

    private Task AddActionStepAsync()
    {
        AddStep(MacroStep.Execute(MacroActionOptions.FirstOrDefault()?.Id ?? 0));
        return Task.CompletedTask;
    }

    private Task AddDelayStepAsync()
    {
        AddStep(MacroStep.Delay(500));
        return Task.CompletedTask;
    }

    private void EditorChanged()
    {
        UpdateValidation();
        if (loadingEditor || disposed) return;

        var validation = HostActionValidator.Validate(
            Name, SelectedKindOption.Kind, Target, CurrentSteps(), registry.GetById,
            CurrentAudioOutput());
        if (!validation.IsValid)
        {
            lock (autosaveSync)
            {
                revision++;
                pendingDraft = null;
                debounce?.Cancel();
                debounce?.Dispose();
                debounce = null;
            }
            Feedback = "Cambios pendientes: completa los campos indicados.";
            return;
        }

        CancellationTokenSource scheduled;
        lock (autosaveSync)
        {
            revision++;
            pendingDraft = new HostActionDraft(
                editorSession, revision, editingActionId, Name,
                SelectedKindOption.Kind, Target, CurrentSteps(), CurrentAudioOutput());
            debounce?.Cancel();
            debounce?.Dispose();
            debounce = scheduled = new CancellationTokenSource();
            pendingTask = RunDebounceAsync(scheduled);
        }
        Feedback = "Cambios pendientes…";
    }

    private async Task RunDebounceAsync(CancellationTokenSource scheduled)
    {
        try
        {
            await Task.Delay(TimeSpan.FromMilliseconds(500), scheduled.Token);
            lock (autosaveSync)
            {
                if (!ReferenceEquals(debounce, scheduled)) return;
                debounce = null;
            }
            await SavePendingAsync();
        }
        catch (OperationCanceledException) when (scheduled.IsCancellationRequested) { }
        finally { scheduled.Dispose(); }
    }

    private async Task SavePendingAsync()
    {
        await saveGate.WaitAsync();
        try
        {
            HostActionDraft? draft;
            lock (autosaveSync) draft = pendingDraft;
            if (draft is null) return;

            try
            {
                Feedback = "Guardando automáticamente…";
                var saved = draft.ActionId is uint actionId
                    ? await registry.UpdateAsync(new HostActionDefinition(
                        actionId, draft.Name, draft.Kind,
                        draft.Kind is HostActionKind.Macro or
                            HostActionKind.SetAudioOutput or
                            HostActionKind.ToggleAudioOutput ? null : draft.Target,
                        draft.Steps, draft.AudioOutput))
                    : await registry.CreateAsync(
                        draft.Name, draft.Kind, draft.Target,
                        draft.Steps, draft.AudioOutput);

                var isLatest = false;
                lock (autosaveSync)
                {
                    if (draft.ActionId is null &&
                        pendingDraft is { ActionId: null } current &&
                        current.EditorSession == draft.EditorSession)
                    {
                        pendingDraft = current with { ActionId = saved.Id };
                    }
                    if (revision == draft.Revision)
                    {
                        pendingDraft = null;
                        isLatest = true;
                    }
                }

                if (editorSession == draft.EditorSession)
                    editingActionId = saved.Id;
                if (isLatest)
                {
                    var keepEditing = editorSession == draft.EditorSession;
                    ApplySavedAction(saved, keepEditing);
                    if (keepEditing) Feedback = "Guardado automáticamente.";
                }
            }
            catch (Exception exception)
            {
                lock (autosaveSync)
                    if (revision == draft.Revision)
                        Feedback = $"No se pudo guardar automáticamente: {exception.Message}";
            }
        }
        finally { saveGate.Release(); }
    }

    private void CancelPendingDelete(uint actionId)
    {
        lock (autosaveSync)
        {
            revision++;
            if (pendingDraft?.ActionId == actionId) pendingDraft = null;
            debounce?.Cancel();
            debounce?.Dispose();
            debounce = null;
        }
    }

    private void ApplySavedAction(HostActionDefinition saved, bool keepEditing)
    {
        ReplaceOrAdd(Actions, saved, true);
        if (saved.Kind == HostActionKind.Macro)
            ReplaceOrAdd(Macros, saved, true);
        else
            RemoveById(Macros, saved.Id);
        if (saved.Kind is HostActionKind.LaunchApplication or HostActionKind.OpenUrl)
            ReplaceOrAdd(MacroActionOptions, saved, true);
        else
            RemoveById(MacroActionOptions, saved.Id);

        if (keepEditing)
        {
            selectedAction = saved;
            OnPropertyChanged(nameof(SelectedAction));
        }
        OnPropertyChanged(nameof(ActionsEmptyVisibility));
        OnPropertyChanged(nameof(MacrosEmptyVisibility));
        foreach (var step in MacroSteps) step.RefreshResolution();
        ActionsChanged?.Invoke(this, EventArgs.Empty);
    }

    private static void ReplaceOrAdd(
        ObservableCollection<HostActionDefinition> collection,
        HostActionDefinition value,
        bool sort)
    {
        var existing = collection
            .Select((item, index) => (item, index))
            .FirstOrDefault(pair => pair.item.Id == value.Id);
        if (existing.item is not null) collection[existing.index] = value;
        else collection.Add(value);
        if (!sort) return;
        for (var index = collection.IndexOf(value); index > 0 &&
             collection[index - 1].Id > value.Id; index--)
            collection.Move(index, index - 1);
    }

    private static void RemoveById(
        ObservableCollection<HostActionDefinition> collection, uint id)
    {
        var existing = collection.FirstOrDefault(item => item.Id == id);
        if (existing is not null) collection.Remove(existing);
    }

    private async Task DeleteAsync()
    {
        if (SelectedAction is null) return;
        var usageCount = registry.GetAll().Count(action =>
            action.Kind == HostActionKind.Macro &&
            action.Steps?.Any(step => step.Kind == MacroStepKind.ExecuteHostAction &&
                                      step.ActionId == SelectedAction.Id) == true);
        if (!await interaction.ConfirmDeleteAsync(SelectedAction, usageCount)) return;
        try
        {
            var deletedId = SelectedAction.Id;
            CancelPendingDelete(deletedId);
            if (await registry.DeleteAsync(deletedId))
            {
                Refresh();
                editorSession++;
                editingActionId = null;
                selectedAction = null;
                OnPropertyChanged(nameof(SelectedAction));
                loadingEditor = true;
                try
                {
                    Name = string.Empty;
                    Target = string.Empty;
                    ClearMacroSteps();
                    SelectedPrimaryAudioDevice = null;
                    SelectedSecondaryAudioDevice = null;
                    UpdateValidation();
                }
                finally { loadingEditor = false; }
                Feedback = $"Host Action {deletedId} eliminada.";
            }
        }
        catch (Exception exception)
        {
            Feedback = $"No se pudo eliminar: {exception.Message}";
        }
    }

    private void Refresh(uint? selectedId = null)
    {
        var id = selectedId ?? SelectedAction?.Id;
        Actions.Clear();
        foreach (var action in registry.GetAll()) Actions.Add(action);
        Macros.Clear();
        foreach (var macro in Actions.Where(action => action.Kind == HostActionKind.Macro))
            Macros.Add(macro);
        OnPropertyChanged(nameof(ActionsEmptyVisibility));
        OnPropertyChanged(nameof(MacrosEmptyVisibility));
        MacroActionOptions.Clear();
        foreach (var action in Actions.Where(action =>
                     action.Kind is HostActionKind.LaunchApplication or
                         HostActionKind.OpenUrl))
            MacroActionOptions.Add(action);
        foreach (var step in MacroSteps) step.RefreshResolution();
        SelectedAction = id.HasValue
            ? Actions.FirstOrDefault(action => action.Id == id.Value) : null;
        ActionsChanged?.Invoke(this, EventArgs.Empty);
        UpdateValidation();
    }

    private IReadOnlyList<MacroStep>? CurrentSteps() =>
        SelectedKindOption.Kind == HostActionKind.Macro
            ? MacroSteps.Select(step => step.ToModel()).ToArray() : null;

    private AudioOutputConfiguration? CurrentAudioOutput() =>
        SelectedKindOption.Kind is HostActionKind.SetAudioOutput or
            HostActionKind.ToggleAudioOutput
            ? new AudioOutputConfiguration(
                SelectedPrimaryAudioDevice?.Id ?? string.Empty,
                SelectedKindOption.Kind == HostActionKind.ToggleAudioOutput
                    ? SelectedSecondaryAudioDevice?.Id : null,
                SelectedPrimaryAudioDevice?.DisplayName,
                SelectedKindOption.Kind == HostActionKind.ToggleAudioOutput
                    ? SelectedSecondaryAudioDevice?.DisplayName : null)
            : null;

    private async Task RefreshAudioDevicesAsync(
        CancellationToken cancellationToken = default)
    {
        var primary = SelectedPrimaryAudioDevice;
        var secondary = SelectedSecondaryAudioDevice;
        try
        {
            var available = await audioOutputService.GetActiveOutputsAsync(cancellationToken);
            AudioDevices.Clear();
            foreach (var device in available) AudioDevices.Add(device);
            SelectedPrimaryAudioDevice = ResolveAudioDevice(primary);
            SelectedSecondaryAudioDevice = ResolveAudioDevice(secondary);
            Feedback = $"{available.Count} salidas de audio detectadas.";
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception exception)
        {
            Feedback = $"No se pudieron actualizar los dispositivos de audio: {exception.Message}";
        }
    }

    private void LoadAudioSelection(AudioOutputConfiguration? audio)
    {
        SelectedPrimaryAudioDevice = ResolveAudioDevice(
            audio?.PrimaryDeviceId, audio?.PrimaryDeviceName);
        SelectedSecondaryAudioDevice = ResolveAudioDevice(
            audio?.SecondaryDeviceId, audio?.SecondaryDeviceName);
    }

    private AudioOutputDevice? ResolveAudioDevice(AudioOutputDevice? previous) =>
        previous is null ? null : ResolveAudioDevice(previous.Id, previous.DisplayName);

    private AudioOutputDevice? ResolveAudioDevice(string? id, string? knownName)
    {
        if (string.IsNullOrWhiteSpace(id)) return null;
        var available = AudioDevices.FirstOrDefault(device => string.Equals(
            device.Id, id, StringComparison.OrdinalIgnoreCase));
        if (available is not null) return available;
        var missing = new AudioOutputDevice(
            id, $"Dispositivo no disponible: {knownName ?? id}", false);
        AudioDevices.Add(missing);
        return missing;
    }

    private void LoadMacroSteps(IReadOnlyList<MacroStep>? steps)
    {
        ClearMacroSteps();
        if (steps is null) return;
        foreach (var step in steps) AddStep(step, false);
    }

    private void AddStep(MacroStep step, bool updateValidation = true)
    {
        var editor = new MacroStepEditorViewModel(
            step, MacroActionOptions, item => MoveStep(item, -1),
            item => MoveStep(item, 1), RemoveStep);
        editor.PropertyChanged += OnMacroStepChanged;
        MacroSteps.Add(editor);
        RefreshStepPositions();
        if (updateValidation) EditorChanged();
    }

    private void ClearMacroSteps()
    {
        foreach (var step in MacroSteps) step.PropertyChanged -= OnMacroStepChanged;
        MacroSteps.Clear();
        RefreshStepPositions();
    }

    private void MoveStep(MacroStepEditorViewModel step, int offset)
    {
        var oldIndex = MacroSteps.IndexOf(step);
        var newIndex = oldIndex + offset;
        if (oldIndex < 0 || newIndex < 0 || newIndex >= MacroSteps.Count) return;
        MacroSteps.Move(oldIndex, newIndex);
        RefreshStepPositions();
        EditorChanged();
    }

    private void RemoveStep(MacroStepEditorViewModel step)
    {
        step.PropertyChanged -= OnMacroStepChanged;
        MacroSteps.Remove(step);
        RefreshStepPositions();
        EditorChanged();
    }

    private void OnMacroStepChanged(object? sender, PropertyChangedEventArgs args) =>
        EditorChanged();

    private void RefreshStepPositions()
    {
        for (var index = 0; index < MacroSteps.Count; index++)
            MacroSteps[index].Position = index + 1;
    }

    public async ValueTask DisposeAsync()
    {
        Task scheduled;
        lock (autosaveSync)
        {
            if (disposed) return;
            disposed = true;
            debounce?.Cancel();
            debounce?.Dispose();
            debounce = null;
            scheduled = pendingTask;
        }
        try { await scheduled; }
        catch (OperationCanceledException) { }
        await SavePendingAsync();
        saveGate.Dispose();
    }

    private void UpdateValidation()
    {
        ValidationMessage = HostActionValidator.Validate(
            Name, SelectedKindOption.Kind, Target, CurrentSteps(), registry.GetById,
            CurrentAudioOutput()).Message;
    }

    private sealed record HostActionDraft(
        long EditorSession,
        long Revision,
        uint? ActionId,
        string Name,
        HostActionKind Kind,
        string Target,
        IReadOnlyList<MacroStep>? Steps,
        AudioOutputConfiguration? AudioOutput);
}

public sealed class MacroStepEditorViewModel : ObservableObject
{
    private readonly ObservableCollection<HostActionDefinition> actionOptions;
    private uint actionId;
    private HostActionDefinition? selectedAction;
    private double delayMilliseconds;
    private int position;

    public MacroStepEditorViewModel(
        MacroStep step,
        ObservableCollection<HostActionDefinition> actionOptions,
        Action<MacroStepEditorViewModel> moveUp,
        Action<MacroStepEditorViewModel> moveDown,
        Action<MacroStepEditorViewModel> remove)
    {
        Kind = step.Kind;
        this.actionOptions = actionOptions;
        actionId = step.ActionId;
        delayMilliseconds = step.DelayMilliseconds;
        MoveUpCommand = new AsyncRelayCommand(_ => Run(moveUp));
        MoveDownCommand = new AsyncRelayCommand(_ => Run(moveDown));
        RemoveCommand = new AsyncRelayCommand(_ => Run(remove));
        RefreshResolution();
    }

    public MacroStepKind Kind { get; }
    public ObservableCollection<HostActionDefinition> ActionOptions => actionOptions;
    public string KindText => Kind == MacroStepKind.ExecuteHostAction ? "Acción" : "Espera";
    public int Position
    {
        get => position;
        set => SetProperty(ref position, value);
    }
    public Visibility ActionVisibility => Kind == MacroStepKind.ExecuteHostAction
        ? Visibility.Visible : Visibility.Collapsed;
    public Visibility DelayVisibility => Kind == MacroStepKind.Delay
        ? Visibility.Visible : Visibility.Collapsed;
    public string MissingActionText =>
        Kind == MacroStepKind.ExecuteHostAction && SelectedAction is null
            ? $"Acción {actionId} no encontrada" : string.Empty;
    public ICommand MoveUpCommand { get; }
    public ICommand MoveDownCommand { get; }
    public ICommand RemoveCommand { get; }

    public HostActionDefinition? SelectedAction
    {
        get => selectedAction;
        set
        {
            if (!SetProperty(ref selectedAction, value)) return;
            if (value is not null) actionId = value.Id;
            OnPropertyChanged(nameof(MissingActionText));
        }
    }

    public double DelayMilliseconds
    {
        get => delayMilliseconds;
        set => SetProperty(ref delayMilliseconds, value);
    }

    public MacroStep ToModel() => Kind == MacroStepKind.ExecuteHostAction
        ? MacroStep.Execute(actionId)
        : MacroStep.Delay(double.IsFinite(DelayMilliseconds) &&
                          DelayMilliseconds == Math.Truncate(DelayMilliseconds) &&
                          DelayMilliseconds is >= int.MinValue and <= int.MaxValue
            ? (int)DelayMilliseconds : 0);

    public void RefreshResolution()
    {
        if (Kind == MacroStepKind.ExecuteHostAction)
            SelectedAction = ActionOptions.FirstOrDefault(action => action.Id == actionId);
    }

    private Task Run(Action<MacroStepEditorViewModel> action)
    {
        action(this);
        return Task.CompletedTask;
    }
}

public sealed record HostActionKindOption(string Name, HostActionKind Kind)
{
    public override string ToString() => Name;
}
